name: CI

on:
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Install package dependencies
              run: npm i

            - name: Build
              run: npm run build
            - name: Install packages deps for example app
              run: cd example-app && npm i

            - name: Cypress run
              uses: cypress-io/github-action@v5
              with:
                  component: true
                  project: ./example-app
                  browser: chrome
